import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://practicesoftwaretesting.com/');
    await page.locator('[data-test="nav-sign-in"]').click();
    await page.locator('[data-test="email"]').click();
    await page.locator('[data-test="email"]').fill('customer@practicesoftwaretesting.com');
    await page.locator('[data-test="password"]').click();
    await page.locator('[data-test="password"]').fill('welcome01');
    await page.locator('[data-test="login-submit"]').click();
    await page.locator('[data-test="nav-home"]').click();
    await page.locator('[data-test="product-01JC91AKSFH6CVDQ9T7G4TRDH5"]').click();
    await page.locator('[data-test="increase-quantity"]').click();
    await page.locator('[data-test="increase-quantity"]').click();
    await page.locator('[data-test="add-to-cart"]').click();
    await page.getByLabel('Product added to shopping').click();
    await page.locator('[data-test="nav-cart"]').click();
    await page.locator('[data-test="proceed-1"]').click();
    await page.locator('[data-test="proceed-2"]').click();
    await page.locator('[data-test="state"]').click();
    await page.locator('[data-test="state"]').fill('Canada');
    await page.locator('[data-test="postcode"]').click();
    await page.locator('[data-test="postcode"]').fill('90000');
    await page.locator('[data-test="proceed-3"]').click();
    await page.locator('[data-test="payment-method"]').selectOption('cash-on-delivery');
    await page.locator('[data-test="finish"]').click();
    await page.getByText('Payment was successful').click();
    await page.locator('[data-test="finish"]').click();
    await page.getByText('Thanks for your order! Your').click();
});